### ISSUE TITLE
IAP 영수증 누락건 log 추적 및 원인 파악

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.IAP#249]
IAP 에 영수증 누락건이 지속적으로 생기고 있다.
lambda log 에 어떤 문제가 있는지 정보가 추가적으로 있어서 이를 통해 어떻게 이런 상황이 벌어지는지 확인하고, 이를 바탕으로 해결책을 찾는다.

**Comment by U-lis** [comment]
log 상으로는 어떤 경과로 해당 결과가 발생했는지 알기가 어렵다.
unity IAP package 안에서 어떤 일이 발생한 것 같은데, 이는 중간에 로그를 빼서 서버에 저장하기가 어렵기 때문에 서버 로그로는 한계가 있다.
[참고](https://planetariumhq.slack.com/archives/C059GDL2C92/p1711416756344489)

**Comment by ipdae** [comment]
- v160 에서 클라이언트 내부 exception msg 를 찍도록 추가했습니다.
- unity 내부 패키지 버전이 낮은걸 확인해서 패키지 업데이트를 시도합니다. https://github.com/planetarium/NineChronicles/issues/4643

**Comment by U-lis** [comment]
main 로비에 들어갔을 때 client 가 category 를 한번 받아서 가지고 있던가 하는 게 있는데, 이거랑 shop 이랑 데이터가 꼬이면서 충돌이 나는 경우 결제가 성공한 이후 처리가 정상적으로 되지 않아 purchase 정보를 IAP쪽으로 보내지 못하는 경우가 있었다. 이를 해결한 뒤 seasonpass 상품에서 발생하던 현상은 거의 사라짐.

**Comment by U-lis** [comment]
여전히 간간이 영수증 누락건이 발생하기는 한다.
역시나 server 쪽에 아예 요청 자체가 오지 않는 현상으로 보이며, 빈도가 낮아 일단 지금은 수동으로 처리하고 있다.
