### ISSUE TITLE
GCASH 구매건 상품 지급 안되는 현상 조사

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.IAP#284]
https://www.notion.so/planetarium/GCASH-1e82eeb75ce14230bc04d5ba691162ea?pvs=4

**Comment by jonny-jeahyunchoi** [comment]
https://developer.android.com/google/play/billing/release-notes?hl=ko
혹시 클라에서 사용하고있는 결제라이브러리 지원문제인가 했는데 노트에는 결제플렛폼관련된 지원내용은 딱히 없네요
